tinymce.addI18n('ro_RO',{
"Redo": "Refaceţi",
"Undo": "Revocare",
"Cut": "Tăiere",
"Copy": "Copiere",
"Paste": "Lipire",
"Select all": "Selectează tot",
"New document": "Document nou",
"Ok": "OK",
"Cancel": "Anulare",
"Visual aids": "Ajutor vizual",
"Bold": "Bold",
"Italic": "Italic",
"Underline": "Subliniere",
"Strikethrough": "Pasajele tăiate",
"Superscript": "Exponent",
"Subscript": "indice inferior",
"Clear formatting": "Anulați formatarea",
"Align left": "Aliniați la stânga",
"Align center": "Centrare",
"Align right": "Aliniați la dreapta",
"Justify": "Ajustare",
"Bullet list": "listă cu marcatori",
"Numbered list": "Lista numerotată",
"Decrease indent": "Redu indentarea",
"Increase indent": "Mărește indentarea",
"Close": "Închide",
"Formats": "Formate",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Browserul dvs. nu suportă acces direct la clipboard. Vă rugăm să utilizați comenzile rapide de la tastatură Ctrl + X \ / C \ / V.",
"Headers": "Antete",
"Header 1": "Antet 1",
"Header 2": "Antet 2",
"Header 3": "Antet 3",
"Header 4": "Antet 4",
"Header 5": "Antet 5",
"Header 6": "Antet 6",
"Headings": "Titluri",
"Heading 1": "Titlul 1",
"Heading 2": "Titlul 2",
"Heading 3": "Titlul 3",
"Heading 4": "Titlul 4",
"Heading 5": "Titlul 5",
"Heading 6": "Titlul 6",
"Preformatted": "Preformatat",
"Div": "Div",
"Pre": "Pre",
"Code": "Code",
"Paragraph": "Paragraf",
"Blockquote": "Blockquote",
"Inline": "Alineat",
"Blocks": "Blocheaza",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Lipirea este acum în modul text simplu. Conținutul va fi inserat ca text simplu, până când dezactivați această opțiune.",
"Fonts": "Fonturi",
"Font Sizes": "Dimensiunile fontului",
"Class": "Categorie",
"Browse for an image": "Căutați o imagine",
"OR": "SAU",
"Drop an image here": "Adaugați o imagine aici",
"Upload": "Încărcați",
"Block": "Blocați",
"Align": "Aliniați",
"Default": "Mod default",
"Circle": "încercuire",
"Disc": "Disc",
"Square": "Pătrat9",
"Lower Alpha": "Alpha minuscule",
"Lower Greek": "Grec minuscule",
"Lower Roman": "Roman minuscule",
"Upper Alpha": "Alpha majuscule",
"Upper Roman": "Roman majuscule",
"Anchor...": "Ancoră...",
"Name": "Nume",
"Id": "Id",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "Id-ul ar trebui să înceapă cu o literă, urmată doar de litere, numere, cratime, puncte, două puncte sau subliniere",
"You have unsaved changes are you sure you want to navigate away?": "Aveți modificări nesalvate sunteți sigur că doriți să navigați departe?",
"Restore last draft": "Restaurați la ultima versiune",
"Special characters...": "Caractere special...",
"Source code": "Cod sursă",
"Insert\/Edit code sample": "Inserare\/modificare a unui exemplu de cod",
"Language": "Limbă",
"Code sample...": "Exemplu de cod...",
"Color Picker": "Alegere culoare",
"R": "R",
"G": "V",
"B": "B",
"Left to right": "Stânga la dreapta",
"Right to left": "Dreapta la stânga",
"Emoticons...": "Emoticoane...",
"Metadata and Document Properties": "Proprietăți de metadate și documente",
"Title": "Title",
"Keywords": "Cuvinte cheie",
"Description": "Descriere",
"Robots": "Roboți",
"Author": "Autor",
"Encoding": "Codare",
"Fullscreen": "Tot ecranul",
"Action": "Acțiune",
"Shortcut": "Scurtătură",
"Help": "Ajutor",
"Address": "Adresă",
"Focus to menubar": "Focus pe bara de menu",
"Focus to toolbar": "Focus pe bata de instrumente",
"Focus to element path": "Focus pe proveniența elementului",
"Focus to contextual toolbar": "Focus pe bara de instrumente contextuale",
"Insert link (if link plugin activated)": "Inserați link (dacă este activat pluginul de linkuri)",
"Save (if save plugin activated)": "Salvați (dacă pluginul de salvare este activat)",
"Find (if searchreplace plugin activated)": "Găsiți (dacă este activat pluginul de căutare)",
"Plugins installed ({0}):": "Plugin-uri instalate ({0}) : ",
"Premium plugins:": "Plugin premium :",
"Learn more...": "Aflați mai multe...",
"You are using {0}": "Utilizați {0}",
"Plugins": "Pluginuri",
"Handy Shortcuts": "Comenzi rapide",
"Horizontal line": "Linie orizontală",
"Insert\/edit image": "Inserați \ / editați o imagine",
"Image description": "Descrierea imaginii",
"Source": "Sursa",
"Dimensions": "Dimensiuni",
"Constrain proportions": "Restrângerea proporțiile",
"General": "General",
"Advanced": "Avansat",
"Style": "Stil",
"Vertical space": "Spațiu vertical",
"Horizontal space": "Spațiu orizontal",
"Border": "Chenar",
"Insert image": "Inserați o imagine",
"Image...": "Imagine...",
"Image list": "Listă de imagini",
"Rotate counterclockwise": "Rotiți în sens invers acelor de ceasornic",
"Rotate clockwise": "Roteste in sensul acelor de ceasornic",
"Flip vertically": "Rotiți vertical",
"Flip horizontally": "Rotiți orizontal",
"Edit image": "Editează imaginea",
"Image options": "Opţiunile imaginii",
"Zoom in": "Mărire",
"Zoom out": "Micșorare",
"Crop": "Decupare",
"Resize": "Redimensionare",
"Orientation": "Orientare",
"Brightness": "Luminozitate",
"Sharpen": "Ascuţire",
"Contrast": "Contrast",
"Color levels": "Nivele de culoare",
"Gamma": "Gamma",
"Invert": "Inversează",
"Apply": "Aplică",
"Back": "Întoarcere",
"Insert date\/time": "Inserează data\/ora",
"Date\/time": "Data\/ora",
"Insert\/Edit Link": "Inserează\/Modifică Link",
"Insert\/edit link": "inserează\/modifică link",
"Text to display": "Text de afișat",
"Url": "Url",
"Open link in...": "Deschide link în...",
"Current window": "Fereastră curentă",
"None": "Nici un rezultat",
"New window": "Fereastră nouă",
"Remove link": "Eliminați linkul",
"Anchors": "Ancore",
"Link...": "Link...",
"Paste or type a link": "Lipiți sau tastați un link",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Adresa URL introdusă pare a fi o adresă de e-mail. Doriți să adăugați prefixul necesar mailto:?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Adresa URL introdusă pare a fi un link extern. Doriți să adăugați prefixul http: \ / \ / necesar?",
"Link list": "Lista de link-uri",
"Insert video": "Inserare videoclip",
"Insert\/edit video": "Introduceți \ / editați videoclipuri",
"Insert\/edit media": "Introduceți \ / editați media",
"Alternative source": "Sursa alternativă",
"Alternative source URL": "URL sursă alternativă",
"Media poster (Image URL)": "Afis media (URL imagine)",
"Paste your embed code below:": "Lipiți codul de încorporare de mai jos:",
"Embed": "Încorporați",
"Media...": "Media...",
"Nonbreaking space": "spațiu fără întreruperi",
"Page break": "Întrerupere de pagină",
"Paste as text": "lipiți ca text",
"Preview": "Previzualizare",
"Print...": "Printare...",
"Save": "Salvare",
"Find": "Căutare",
"Replace with": "Înlocuiți cu",
"Replace": "Înlocuiți",
"Replace all": "Înlocuiți tot",
"Previous": "Anterior",
"Next": "Următor",
"Find and replace...": "Găsiți și înlocuiți...",
"Could not find the specified string.": "Nu s-a putut găsi șirul specificat.",
"Match case": "Potrivire",
"Find whole words only": "găsiți numai cuvinte întregi",
"Spell check": "Verificare a ortografiei",
"Ignore": "Ignoră",
"Ignore all": "Ignoră tot",
"Finish": "Finalizarea",
"Add to Dictionary": "Adăugați la dicționar",
"Insert table": "Introduceți tabel",
"Table properties": "Proprietățile tabelului",
"Delete table": "Ștergeți tabelul",
"Cell": "Celulă",
"Row": "Rând",
"Column": "Coloană",
"Cell properties": "Proprietățile celulelor",
"Merge cells": "Uneste celulele",
"Split cell": "Desparte celulele",
"Insert row before": "Inserați un rând înainte",
"Insert row after": "Introduceți rând după",
"Delete row": "Ștergeți rândul",
"Row properties": "Proprietățile rândului",
"Cut row": "Decupați rândul",
"Copy row": "Copiați rândul",
"Paste row before": "Lipiți rândul înainte",
"Paste row after": "Lipiți rândul după",
"Insert column before": "Introduceți coloana înainte",
"Insert column after": "Introduceți coloana după",
"Delete column": "Ștergeți coloana",
"Cols": "Coloane",
"Rows": "Rânduri",
"Width": "Lăţime",
"Height": "Înălţime",
"Cell spacing": "Distanță intre celule",
"Cell padding": "Spații între celule",
"Show caption": "Afișare legendă",
"Left": "Stânga",
"Center": "Centru",
"Right": "Dreapta",
"Cell type": "Tip de celulă",
"Scope": "Scop",
"Alignment": "Aliniament",
"H Align": "Aliniament H",
"V Align": "Aliniament V",
"Top": "Partea de sus",
"Middle": "Mijloc",
"Bottom": "Partea de jos",
"Header cell": "Celula antet",
"Row group": "Grup de rânduri",
"Column group": "Grup de coloane",
"Row type": "Tip de rânduri",
"Header": "Antet",
"Body": "Corp",
"Footer": "Subsol pagină",
"Border color": "Culoarea chenarului",
"Insert template...": "Introduceți șablonul...",
"Templates": "Șabloanele",
"Template": "Șablon",
"Text color": "Culoare text",
"Background color": "Culoare fundal",
"Custom...": "Personalizare...",
"Custom color": "Culoare customizată",
"No color": "Fără culoare",
"Remove color": "Eliminați culoarea",
"Table of Contents": "Cuprins",
"Show blocks": "Afișați blocuri",
"Show invisible characters": "Afișare caractere invizibile",
"Word count": "Număr de cuvinte",
"Words: {0}": "Cuvinte : {0}",
"{0} words": "{0} cuvinte",
"File": "Fişier",
"Edit": "Editați",
"Insert": "Inserare",
"View": "Vizualizare",
"Format": "Format",
"Table": "Tabel",
"Tools": "Unelte",
"Powered by {0}": "Cu sprijinul {0}",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Zonă cu text bogat. Apăsați ALT-F9 pentru meniu. Apăsați ALT-F10 pentru bara de instrumente. Apăsați ALT-0 pentru ajutor.",
"Image title": "Titlul imaginii",
"Border width": "Lățimea marginii",
"Border style": "Stilul marginii",
"Error": "Eroare",
"Warn": "Avertizment",
"Valid": "Validare",
"To open the popup, press Shift+Enter": "Pentru a deschide fereastra, apăsați Shift + Enter",
"Rich Text Area. Press ALT-0 for help.": "Zona cu text bogat. Apăsați ALT-0 pentru ajutor.",
"System Font": "Fonturi sistem",
"Failed to upload image: {0}": "Nu a putut încărca imaginea: {0}",
"Failed to load plugin: {0} from url {1}": "Nu a reușit încărcarea pluginului: {0} din URL {1} ",
"Failed to load plugin url: {0}": "Nu a putut încărca URL-ul pluginului: {0}",
"Failed to initialize plugin: {0}": "Initializarea pluginului nu a reusit: {0}",
"example": "exemplu",
"Search": "Căutare",
"All": "Tot",
"Currency": "Valută",
"Text": "Text",
"Quotations": "Citate",
"Mathematical": "Matematic",
"Extended Latin": "Latină extinsă",
"Symbols": "Simboluri",
"Arrows": "Săgeți",
"User Defined": "Definit de utilizator",
"dollar sign": "Simbolul dolarului",
"currency sign": "Simbolul valută",
"euro-currency sign": "Simbolul euro-monedă",
"colon sign": "Simbolul coloanei",
"cruzeiro sign": "Simbolul cruzeiro",
"french franc sign": "Simbolul francului francez",
"lira sign": "Simbolul lirei",
"mill sign": "Simbolul morii",
"naira sign": "Simbolul naira",
"peseta sign": "Simbolul peseta",
"rupee sign": "Simbolul roupie",
"won sign": "Simbolul won",
"new sheqel sign": "Simbolul sheqel nou",
"dong sign": "Simbolul dong",
"kip sign": "Simbolul kip",
"tugrik sign": "Simbolul tougrik",
"drachma sign": "Simbolul drachme",
"german penny symbol": "Simbolul bănuț german",
"peso sign": "Simbolul peso",
"guarani sign": "Simbolul guarani",
"austral sign": "Simbolul austral",
"hryvnia sign": "Simbolul Hryvnia",
"cedi sign": "Simbolul cedi",
"livre tournois sign": "Simbolul livre tournois",
"spesmilo sign": "Simbolul spesmilo",
"tenge sign": "Simbolul tenge",
"indian rupee sign": "Simbolul roupie indiană",
"turkish lira sign": "Simbolul de liră turcească",
"nordic mark sign": "Simbolul mărcii nordice",
"manat sign": "Simbolul manat",
"ruble sign": "Simbolul ruble",
"yen character": "Caracterul Yen",
"yuan character": "Caracterul Yuan",
"yuan character, in hong kong and taiwan": "caracter yuani, în Hong Kong și Taiwan",
"yen\/yuan character variant one": "yen \ / yuanul variantă de caractere numărul unu",
"Loading emoticons...": "Se încarcă emoticoane...",
"Could not load emoticons": "Nu s-au putut încărca emoticoanele",
"People": "Persoane",
"Animals and Nature": "Animale și natură",
"Food and Drink": "Mâncare și băutură",
"Activity": "Activitate",
"Travel and Places": "Călătorii și locuri de vizitat",
"Objects": "Obiecte",
"Flags": "Steaguri",
"Characters": "Caractere",
"Characters (no spaces)": "Caractere (fără spații)",
"Error: Form submit field collision.": "Eroare: Trimiterea formularului conține coliziune de câmpuri",
"Error: No form element found.": "Eroare: Nici o formă element de găsit.",
"Update": "Actualizare",
"Color swatch": "Specimenului de culoare",
"Turquoise": "Turcoaz",
"Green": "Verde",
"Blue": "Albastru",
"Purple": "Violet",
"Navy Blue": "Albastru marin",
"Dark Turquoise": "Turcoaz închis",
"Dark Green": "Verde închis",
"Medium Blue": "Albastru mediu",
"Medium Purple": "Violet mediu",
"Midnight Blue": "Albastru închis",
"Yellow": "Galben",
"Orange": "Portocaliu",
"Red": "Roșu",
"Light Gray": "Gri deschis",
"Gray": "Gri",
"Dark Yellow": "Galben închis",
"Dark Orange": "Portocaliu închis",
"Dark Red": "Roșu închis",
"Medium Gray": "Gri mediu",
"Dark Gray": "Gri închis",
"Black": "Negru",
"White": "Alb",
"Switch to or from fullscreen mode": "Comutați la sau de la modul ecran complet",
"Open help dialog": "Deschideți dialogul de ajutor",
"history": "Istoric",
"styles": "Stiluri",
"formatting": "Formatare",
"alignment": "Alineat",
"indentation": "Indentare",
"permanent pen": "stilou permanent",
"comments": "comentarii",
"Anchor": "Ancore",
"Special character": "Caractere speciale",
"Code sample": "Exemplu de cod",
"Color": "Culoare",
"Emoticons": "Emoticoane",
"Document properties": "Proprietatile documentului",
"Image": "Imagine",
"Insert link": "Introduceți linkul",
"Target": "Ţintă",
"Link": "Link",
"Poster": "Poster",
"Media": "Media",
"Print": "Imprimare",
"Prev": "Anterior",
"Find and replace": "Găsiți și înlocuiți",
"Whole words": "Cuvinte întregi",
"Spellcheck": "Verificare a ortografiei",
"Caption": "Legendă",
"Insert template": "Introduceți șablonul"
});